/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthRedirect: typeof import('./components/account/auth-redirect.vue')['default']
    'Cd.footer': typeof import('./components/base/cd.footer.vue')['default']
    'Cd.spatialCoverageMap': typeof import('./components/search-results/cd.spatial-coverage-map.vue')['default']
    'Cz.login': typeof import('./components/account/cz.login.vue')['default']
    EditDataset: typeof import('./components/landing-page/edit-dataset.vue')['default']
    HsUppy: typeof import('./components/landing-page/hs-uppy.vue')['default']
    LandingPage: typeof import('./components/landing-page/landing-page.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    S3Form: typeof import('./components/landing-page/s3-form.vue')['default']
    Toc: typeof import('./components/base/toc.vue')['default']
  }
}
